# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\UI\UINameEvalStyled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NameEvaluator(object):
    def setupUi(self, NameEvaluator):
        NameEvaluator.setObjectName("NameEvaluator")
        NameEvaluator.resize(1128, 745)
        font = QtGui.QFont()
        font.setPointSize(9)
        NameEvaluator.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\UI\\../../../NameChecker/src/archive/Projects/Old Projects/Name Checkers/genie/lamp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NameEvaluator.setWindowIcon(icon)
        NameEvaluator.setStyleSheet("QWidget{\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QCheckBox{\n"
"width:130%;\n"
"}\n"
"QTableWidget{\n"
"background-color: rgb(240, 240, 240);\n"
"border: 2px solid rgb(200, 200, 200);\n"
"}\n"
"QTableWidget:hover, QTableWidget:focus{\n"
"background-color:rgb(255,255,255);\n"
"}\n"
"QProgressBar{\n"
"background-color: rgb(215, 215, 215);;\n"
"color:white;\n"
"}\n"
"QProgressBar:bar {\n"
"background-color: grey;\n"
"width: 10px;\n"
"margin: 1px;\n"
"}\n"
"QRadioButton:hover{\n"
"color:rgb(100,100,100);\n"
"}\n"
"QTextEdit, QPlainTextEdit, QTextBrowser{\n"
"border: 2px solid rgb(180, 180, 180);\n"
"border-radius: 6px;\n"
"padding: 5px;\n"
"background-color: rgb(240, 240, 240);\n"
"}\n"
"QLineEdit{\n"
"border: 2px solid rgb(180, 180, 180);\n"
"border-radius: 4px;\n"
"background-color: rgb(240, 240, 240);\n"
"}\n"
"QLineEdit:hover, QLineEdit:focus, QTextEdit:hover, QTextEdit:focus, QPlainTextEdit:hover, QPlainTextEdit:focus{\n"
"background-color:rgb(255,255,255);\n"
"}\n"
"QLabel{\n"
"padding-top:5px;\n"
"color: black;\n"
"font: bold;\n"
"}\n"
"QPushButton {\n"
"color: black;\n"
"border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.2, cy: 1.3,\n"
"fx: 1.0, fy: 0.5,\n"
"radius: 1.35, stop: 0 rgb(228, 228, 228), stop: 1 rgb(208, 208, 208));\n"
"min-width: 80px;\n"
"font: bold;\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed {\n"
"color:blue;\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 rgb(245, 245, 245));\n"
"font:italic;\n"
"}\n"
"QPushButton:hover, QToolButton:hover{\n"
"color:rgb(100,100,100);\n"
"border: 2px solid rgb(200, 200, 200);\n"
"}\n"
"QScrollBar::horizontal {\n"
"max-height: 7px;\n"
"}\n"
"QScrollBar::vertical {\n"
"max-width: 7px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background-color:rgb(200, 200, 200);\n"
"max-width: 4px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background-color:rgb(200, 200, 200);\n"
"max-height: 4px;\n"
"}")
        self.MainWindow = QtWidgets.QWidget(NameEvaluator)
        self.MainWindow.setStyleSheet("opacity: 0;\n"
"font: 10pt \"Cambria\";\n"
"background-color: #55565A;\n"
"")
        self.MainWindow.setObjectName("MainWindow")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MainTab = QtWidgets.QTabWidget(self.MainWindow)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.MainTab.setFont(font)
        self.MainTab.setStyleSheet("QWidget{\n"
"background-color:#006B3F;\n"
"}\n"
"QLabel{\n"
"font: 75 14pt \"Cambria\";\n"
"font-weight:bold;\n"
"color:white;\n"
"}\n"
"QPlainTextEdit {\n"
"background-color:white;\n"
"border-top:1px solid #A9A8A9;\n"
"border-left: 2px solid #A9A8A9;\n"
"border-right: 2px solid #A9A8A9;\n"
"border-bottom: 2px solid #A9A8A9;\n"
"}\n"
"QTableView {\n"
"background-color:white;\n"
"border-top:1px solid #A9A8A9;\n"
"border-left: 2px solid #A9A8A9;\n"
"border-right: 2px solid #A9A8A9;\n"
"border-bottom: 2px solid #A9A8A9;\n"
"}\n"
"QLineEdit{\n"
"background-color: white;\n"
"border-top:1px solid #A9A8A9;\n"
"border-left: 2px solid #A9A8A9;\n"
"border-right: 2px solid #A9A8A9;\n"
"border-bottom: 2px solid #A9A8A9;\n"
"}\n"
"QToolButton{\n"
"background-color: #4F748B;\n"
"border-top:1px solid #9BB7D3;\n"
"border-left: 2px solid #9BB7D3;\n"
"border-right: 2px solid #9BB7D3;\n"
"border-bottom: 5px solid #9BB7D3;\n"
"color:#9BB7D3;\n"
"font-weight:bold;\n"
"}\n"
"QToolButton:hover{\n"
"background-color: #9BB7D3;\n"
"color:white;\n"
"}\n"
"QToolButton:pressed{\n"
"background-color: #9BB7D3;\n"
"color:white;\n"
"border-top:5px solid white;\n"
"border-left: 2px solid white;\n"
"border-right: 2px solid white;\n"
"border-bottom: 1px solid white;\n"
"}\n"
"QPushButton{\n"
"background-color: #006B3F;\n"
"border-top:1px solid #26D07C;\n"
"border-left: 2px solid #26D07C;\n"
"border-right: 2px solid #26D07C;\n"
"border-bottom: 5px solid #26D07C;\n"
"border-radius: 2px;\n"
"color:#26D07C;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#26D07C;\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #006B3F;\n"
"border-top:5px solid white;\n"
"border-left: 2px solid white;\n"
"border-right: 2px solid white;\n"
"border-bottom: 2px solid white;\n"
"border-radius: 2px;\n"
"}\n"
"QGroupBox{\n"
"background-color: #26D07C;\n"
"border:none;\n"
"font-weight:bold;\n"
"}\n"
"QGroupBox:hover{\n"
"background-color: #A9A8A9;\n"
"}\n"
"QCheckBox{\n"
"border: None;\n"
"background-color: None;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"\n"
"QTabWidget QTabBar::tab{\n"
"background-color: #006B3F;\n"
"height: 25px;\n"
"width: 256px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"QTabWidget QTabBar::tab:selected{\n"
"background-color: #26D07C;\n"
"width: 256px;\n"
"color:white;\n"
"}\n"
"QCheckbox{\n"
"border: None;\n"
"background-color: None;\n"
"}\n"
"QScrollBar:vertical {\n"
"background:#9BB7D3;\n"
"}\n"
"QScrollBar:handle{\n"
"background:#4F748B;\n"
"}\n"
"QScrollBar:pressed{\n"
"background:#A9A8A9;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"")
        self.MainTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.MainTab.setObjectName("MainTab")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setStyleSheet("")
        self.main_tab.setObjectName("main_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.main_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.main_tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.main_tab)
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.name_rationale_label_3 = QtWidgets.QLabel(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_rationale_label_3.sizePolicy().hasHeightForWidth())
        self.name_rationale_label_3.setSizePolicy(sizePolicy)
        self.name_rationale_label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_rationale_label_3.setFont(font)
        self.name_rationale_label_3.setStyleSheet("")
        self.name_rationale_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rationale_label_3.setObjectName("name_rationale_label_3")
        self.verticalLayout_2.addWidget(self.name_rationale_label_3, 0, QtCore.Qt.AlignTop)
        self.group_check_uncheck_all = QtWidgets.QGroupBox(self.main_tab)
        self.group_check_uncheck_all.setMouseTracking(False)
        self.group_check_uncheck_all.setStyleSheet("")
        self.group_check_uncheck_all.setCheckable(False)
        self.group_check_uncheck_all.setObjectName("group_check_uncheck_all")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.group_check_uncheck_all)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkbox_all = QtWidgets.QCheckBox(self.group_check_uncheck_all)
        self.checkbox_all.setToolTip("")
        self.checkbox_all.setStyleSheet("")
        self.checkbox_all.setObjectName("checkbox_all")
        self.horizontalLayout_13.addWidget(self.checkbox_all)
        self.verticalLayout_2.addWidget(self.group_check_uncheck_all)
        self.group_inn = QtWidgets.QGroupBox(self.main_tab)
        self.group_inn.setStyleSheet("")
        self.group_inn.setObjectName("group_inn")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.group_inn)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkbox_inn = QtWidgets.QCheckBox(self.group_inn)
        self.checkbox_inn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_inn.sizePolicy().hasHeightForWidth())
        self.checkbox_inn.setSizePolicy(sizePolicy)
        self.checkbox_inn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkbox_inn.setToolTip("")
        self.checkbox_inn.setStyleSheet("")
        self.checkbox_inn.setObjectName("checkbox_inn")
        self.checkboxGroup = QtWidgets.QButtonGroup(NameEvaluator)
        self.checkboxGroup.setObjectName("checkboxGroup")
        self.checkboxGroup.setExclusive(False)
        self.checkboxGroup.addButton(self.checkbox_inn)
        self.horizontalLayout_4.addWidget(self.checkbox_inn)
        self.verticalLayout_2.addWidget(self.group_inn)
        self.group_market_research = QtWidgets.QGroupBox(self.main_tab)
        self.group_market_research.setStyleSheet("")
        self.group_market_research.setObjectName("group_market_research")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.group_market_research)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkbox_market_research = QtWidgets.QCheckBox(self.group_market_research)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_market_research.sizePolicy().hasHeightForWidth())
        self.checkbox_market_research.setSizePolicy(sizePolicy)
        self.checkbox_market_research.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkbox_market_research.setToolTip("")
        self.checkbox_market_research.setObjectName("checkbox_market_research")
        self.checkboxGroup.addButton(self.checkbox_market_research)
        self.horizontalLayout_3.addWidget(self.checkbox_market_research)
        self.verticalLayout_2.addWidget(self.group_market_research)
        self.group_linguistics = QtWidgets.QGroupBox(self.main_tab)
        self.group_linguistics.setObjectName("group_linguistics")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_linguistics)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkbox_linguistic = QtWidgets.QCheckBox(self.group_linguistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_linguistic.sizePolicy().hasHeightForWidth())
        self.checkbox_linguistic.setSizePolicy(sizePolicy)
        self.checkbox_linguistic.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkbox_linguistic.setToolTip("")
        self.checkbox_linguistic.setStyleSheet("")
        self.checkbox_linguistic.setObjectName("checkbox_linguistic")
        self.checkboxGroup.addButton(self.checkbox_linguistic)
        self.horizontalLayout_2.addWidget(self.checkbox_linguistic)
        self.verticalLayout_2.addWidget(self.group_linguistics)
        self.group_competitor = QtWidgets.QGroupBox(self.main_tab)
        self.group_competitor.setObjectName("group_competitor")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.group_competitor)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkbox_competitor = QtWidgets.QCheckBox(self.group_competitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_competitor.sizePolicy().hasHeightForWidth())
        self.checkbox_competitor.setSizePolicy(sizePolicy)
        self.checkbox_competitor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkbox_competitor.setToolTip("")
        self.checkbox_competitor.setStyleSheet("")
        self.checkbox_competitor.setObjectName("checkbox_competitor")
        self.checkboxGroup.addButton(self.checkbox_competitor)
        self.horizontalLayout_5.addWidget(self.checkbox_competitor)
        self.verticalLayout_2.addWidget(self.group_competitor)
        self.group_project_avoids = QtWidgets.QGroupBox(self.main_tab)
        self.group_project_avoids.setObjectName("group_project_avoids")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.group_project_avoids)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkbox_project = QtWidgets.QCheckBox(self.group_project_avoids)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_project.sizePolicy().hasHeightForWidth())
        self.checkbox_project.setSizePolicy(sizePolicy)
        self.checkbox_project.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkbox_project.setToolTip("")
        self.checkbox_project.setStyleSheet("")
        self.checkbox_project.setObjectName("checkbox_project")
        self.checkboxGroup.addButton(self.checkbox_project)
        self.horizontalLayout_7.addWidget(self.checkbox_project)
        self.verticalLayout_2.addWidget(self.group_project_avoids)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_9 = QtWidgets.QFrame(self.main_tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout.addWidget(self.line_9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.name_rationale_label_2 = QtWidgets.QLabel(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_rationale_label_2.sizePolicy().hasHeightForWidth())
        self.name_rationale_label_2.setSizePolicy(sizePolicy)
        self.name_rationale_label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_rationale_label_2.setFont(font)
        self.name_rationale_label_2.setStyleSheet("")
        self.name_rationale_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rationale_label_2.setObjectName("name_rationale_label_2")
        self.verticalLayout_3.addWidget(self.name_rationale_label_2)
        self.text_names = QtWidgets.QPlainTextEdit(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_names.sizePolicy().hasHeightForWidth())
        self.text_names.setSizePolicy(sizePolicy)
        self.text_names.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_names.setFont(font)
        self.text_names.setStyleSheet("")
        self.text_names.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.text_names.setObjectName("text_names")
        self.verticalLayout_3.addWidget(self.text_names)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btn_check_names = QtWidgets.QPushButton(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_check_names.sizePolicy().hasHeightForWidth())
        self.btn_check_names.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_check_names.setFont(font)
        self.btn_check_names.setStyleSheet("")
        self.btn_check_names.setObjectName("btn_check_names")
        self.horizontalLayout_19.addWidget(self.btn_check_names)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_upper_case = QtWidgets.QToolButton(self.main_tab)
        self.btn_upper_case.setToolTip("")
        self.btn_upper_case.setStyleSheet("")
        self.btn_upper_case.setObjectName("btn_upper_case")
        self.horizontalLayout_6.addWidget(self.btn_upper_case)
        self.btn_title_case = QtWidgets.QToolButton(self.main_tab)
        self.btn_title_case.setToolTip("")
        self.btn_title_case.setStyleSheet("")
        self.btn_title_case.setObjectName("btn_title_case")
        self.horizontalLayout_6.addWidget(self.btn_title_case)
        self.btn_lower_case = QtWidgets.QToolButton(self.main_tab)
        self.btn_lower_case.setToolTip("")
        self.btn_lower_case.setStyleSheet("")
        self.btn_lower_case.setObjectName("btn_lower_case")
        self.horizontalLayout_6.addWidget(self.btn_lower_case)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.main_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.name_conflict_label = QtWidgets.QLabel(self.main_tab)
        self.name_conflict_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_conflict_label.sizePolicy().hasHeightForWidth())
        self.name_conflict_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_conflict_label.setFont(font)
        self.name_conflict_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_conflict_label.setObjectName("name_conflict_label")
        self.verticalLayout_7.addWidget(self.name_conflict_label)
        self.qtable_results = QtWidgets.QTableView(self.main_tab)
        self.qtable_results.setStyleSheet("")
        self.qtable_results.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qtable_results.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.qtable_results.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.qtable_results.setObjectName("qtable_results")
        self.qtable_results.verticalHeader().setCascadingSectionResizes(True)
        self.qtable_results.verticalHeader().setMinimumSectionSize(23)
        self.verticalLayout_7.addWidget(self.qtable_results)
        self.lineedit_ignore = QtWidgets.QLineEdit(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_ignore.sizePolicy().hasHeightForWidth())
        self.lineedit_ignore.setSizePolicy(sizePolicy)
        self.lineedit_ignore.setStyleSheet("")
        self.lineedit_ignore.setObjectName("lineedit_ignore")
        self.verticalLayout_7.addWidget(self.lineedit_ignore)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.btn_exit = QtWidgets.QPushButton(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exit.sizePolicy().hasHeightForWidth())
        self.btn_exit.setSizePolicy(sizePolicy)
        self.btn_exit.setMinimumSize(QtCore.QSize(94, 0))
        self.btn_exit.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet(":hover{\n"
"    font: 75 12pt \"Cambria\";\n"
"    background-color:#D0B888;\n"
"    border-color:#D0B888;\n"
"}\n"
"QPushButton{\n"
"background-color: #C1052F;\n"
"color: white;\n"
"border-top:1px solid black;\n"
"border-left: 2px solid black;\n"
"border-right: 2px solid black;\n"
"border-bottom: 3px solid black;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_21.addWidget(self.btn_exit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_21, 2, 0, 1, 1)
        self.MainTab.addTab(self.main_tab, "")
        self.avoids_tab = QtWidgets.QWidget()
        self.avoids_tab.setObjectName("avoids_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.avoids_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 1, 3, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.qtable_avoids = QtWidgets.QTableView(self.avoids_tab)
        self.qtable_avoids.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.qtable_avoids.setSortingEnabled(True)
        self.qtable_avoids.setWordWrap(False)
        self.qtable_avoids.setObjectName("qtable_avoids")
        self.gridLayout_6.addWidget(self.qtable_avoids, 1, 3, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_reload_avoids = QtWidgets.QPushButton(self.avoids_tab)
        self.btn_reload_avoids.setObjectName("btn_reload_avoids")
        self.gridLayout_7.addWidget(self.btn_reload_avoids, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addLayout(self.gridLayout_7, 4, 3, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_filter_avoids = QtWidgets.QToolButton(self.avoids_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_filter_avoids.sizePolicy().hasHeightForWidth())
        self.btn_filter_avoids.setSizePolicy(sizePolicy)
        self.btn_filter_avoids.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_filter_avoids.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btn_filter_avoids.setObjectName("btn_filter_avoids")
        self.horizontalLayout_11.addWidget(self.btn_filter_avoids)
        self.lineedit_filter_avoids = QtWidgets.QLineEdit(self.avoids_tab)
        self.lineedit_filter_avoids.setInputMask("")
        self.lineedit_filter_avoids.setText("")
        self.lineedit_filter_avoids.setObjectName("lineedit_filter_avoids")
        self.horizontalLayout_11.addWidget(self.lineedit_filter_avoids)
        self.btn_clear_avoid_filter = QtWidgets.QToolButton(self.avoids_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_avoid_filter.sizePolicy().hasHeightForWidth())
        self.btn_clear_avoid_filter.setSizePolicy(sizePolicy)
        self.btn_clear_avoid_filter.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_clear_avoid_filter.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btn_clear_avoid_filter.setObjectName("btn_clear_avoid_filter")
        self.horizontalLayout_11.addWidget(self.btn_clear_avoid_filter)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 3, 3, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_all_avoids = QtWidgets.QLabel(self.avoids_tab)
        self.label_all_avoids.setObjectName("label_all_avoids")
        self.horizontalLayout_12.addWidget(self.label_all_avoids, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addLayout(self.horizontalLayout_12, 0, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_project_avoids = QtWidgets.QLabel(self.avoids_tab)
        self.label_project_avoids.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_avoids.setObjectName("label_project_avoids")
        self.horizontalLayout_8.addWidget(self.label_project_avoids)
        self.line_2 = QtWidgets.QFrame(self.avoids_tab)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.label_competitor = QtWidgets.QLabel(self.avoids_tab)
        self.label_competitor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_competitor.setObjectName("label_competitor")
        self.horizontalLayout_8.addWidget(self.label_competitor)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btn_save_avoids = QtWidgets.QPushButton(self.avoids_tab)
        self.btn_save_avoids.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_save_avoids.setObjectName("btn_save_avoids")
        self.gridLayout_8.addWidget(self.btn_save_avoids, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addLayout(self.gridLayout_8, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.text_project_avoids = QtWidgets.QPlainTextEdit(self.avoids_tab)
        self.text_project_avoids.setMaximumSize(QtCore.QSize(300, 16777215))
        self.text_project_avoids.setObjectName("text_project_avoids")
        self.horizontalLayout_9.addWidget(self.text_project_avoids)
        self.line_3 = QtWidgets.QFrame(self.avoids_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        self.text_competitor = QtWidgets.QPlainTextEdit(self.avoids_tab)
        self.text_competitor.setObjectName("text_competitor")
        self.horizontalLayout_9.addWidget(self.text_competitor)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.avoids_tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.MainTab.addTab(self.avoids_tab, "")
        self.gridLayout_2.addWidget(self.MainTab, 0, 0, 1, 1)
        NameEvaluator.setCentralWidget(self.MainWindow)
        self.statusbar = QtWidgets.QStatusBar(NameEvaluator)
        self.statusbar.setObjectName("statusbar")
        NameEvaluator.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(NameEvaluator)
        self.actionExit.setShortcut("")
        self.actionExit.setObjectName("actionExit")
        self.actionView_pharma_avoids = QtWidgets.QAction(NameEvaluator)
        self.actionView_pharma_avoids.setObjectName("actionView_pharma_avoids")
        self.actionView_inn_avoids = QtWidgets.QAction(NameEvaluator)
        self.actionView_inn_avoids.setObjectName("actionView_inn_avoids")
        self.actionProject_avoids = QtWidgets.QAction(NameEvaluator)
        self.actionProject_avoids.setObjectName("actionProject_avoids")
        self.actionInternal_names = QtWidgets.QAction(NameEvaluator)
        self.actionInternal_names.setObjectName("actionInternal_names")
        self.actionPresented_names = QtWidgets.QAction(NameEvaluator)
        self.actionPresented_names.setObjectName("actionPresented_names")
        self.actionCompetitor_names = QtWidgets.QAction(NameEvaluator)
        self.actionCompetitor_names.setObjectName("actionCompetitor_names")
        self.actionOptions = QtWidgets.QAction(NameEvaluator)
        self.actionOptions.setObjectName("actionOptions")
        self.actionTool_1 = QtWidgets.QAction(NameEvaluator)
        self.actionTool_1.setObjectName("actionTool_1")
        self.actionTool_style = QtWidgets.QAction(NameEvaluator)
        self.actionTool_style.setObjectName("actionTool_style")
        self.actionTool_3 = QtWidgets.QAction(NameEvaluator)
        self.actionTool_3.setObjectName("actionTool_3")
        self.actionTool_4 = QtWidgets.QAction(NameEvaluator)
        self.actionTool_4.setObjectName("actionTool_4")
        self.actionTool_5 = QtWidgets.QAction(NameEvaluator)
        self.actionTool_5.setObjectName("actionTool_5")
        self.actionSave_names = QtWidgets.QAction(NameEvaluator)
        self.actionSave_names.setObjectName("actionSave_names")
        self.actionSort_names = QtWidgets.QAction(NameEvaluator)
        self.actionSort_names.setObjectName("actionSort_names")
        self.actionFind_conflicts = QtWidgets.QAction(NameEvaluator)
        self.actionFind_conflicts.setObjectName("actionFind_conflicts")
        self.actionClear_avoids = QtWidgets.QAction(NameEvaluator)
        self.actionClear_avoids.setObjectName("actionClear_avoids")
        self.actionView_stripped_names = QtWidgets.QAction(NameEvaluator)
        self.actionView_stripped_names.setObjectName("actionView_stripped_names")
        self.actionINN_avoids_password_required = QtWidgets.QAction(NameEvaluator)
        self.actionINN_avoids_password_required.setObjectName("actionINN_avoids_password_required")
        self.actionPharma_Avoids_password_req = QtWidgets.QAction(NameEvaluator)
        self.actionPharma_Avoids_password_req.setObjectName("actionPharma_Avoids_password_req")
        self.actionINN_avoids = QtWidgets.QAction(NameEvaluator)
        self.actionINN_avoids.setObjectName("actionINN_avoids")
        self.actionPharma_avoids = QtWidgets.QAction(NameEvaluator)
        self.actionPharma_avoids.setObjectName("actionPharma_avoids")
        self.actionAdd_avoids = QtWidgets.QAction(NameEvaluator)
        self.actionAdd_avoids.setObjectName("actionAdd_avoids")

        self.retranslateUi(NameEvaluator)
        self.MainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NameEvaluator)

    def retranslateUi(self, NameEvaluator):
        _translate = QtCore.QCoreApplication.translate
        NameEvaluator.setWindowTitle(_translate("NameEvaluator", "NameEvaluator"))
        self.label_2.setText(_translate("NameEvaluator", "Name Evaluator"))
        self.label.setText(_translate("NameEvaluator", "<html><head/><body><p><img src=\":/img_/Leaderboard_Icon_RGB.jpg\"/></p></body></html>"))
        self.name_rationale_label_3.setStatusTip(_translate("NameEvaluator", "Choose what you would like to screen against"))
        self.name_rationale_label_3.setText(_translate("NameEvaluator", "Screen against:"))
        self.checkbox_all.setStatusTip(_translate("NameEvaluator", "Check or uncheck all options [Ctrl+Shift+A]"))
        self.checkbox_all.setText(_translate("NameEvaluator", "Check / Uncheck All"))
        self.checkbox_inn.setStatusTip(_translate("NameEvaluator", "Check against INN avoids"))
        self.checkbox_inn.setText(_translate("NameEvaluator", "INN"))
        self.group_market_research.setWhatsThis(_translate("NameEvaluator", "checkboxContainer"))
        self.checkbox_market_research.setStatusTip(_translate("NameEvaluator", "Check against market research avoids"))
        self.checkbox_market_research.setText(_translate("NameEvaluator", "Market Research"))
        self.checkbox_linguistic.setStatusTip(_translate("NameEvaluator", "Check against project specific avoids"))
        self.checkbox_linguistic.setText(_translate("NameEvaluator", "Linguistics"))
        self.checkbox_competitor.setStatusTip(_translate("NameEvaluator", "Check against competitor names"))
        self.checkbox_competitor.setText(_translate("NameEvaluator", "Competitors"))
        self.checkbox_project.setStatusTip(_translate("NameEvaluator", "Check against project avoids"))
        self.checkbox_project.setText(_translate("NameEvaluator", "Project Avoids"))
        self.name_rationale_label_2.setStatusTip(_translate("NameEvaluator", "Your Names without rationale and/or notes"))
        self.name_rationale_label_2.setText(_translate("NameEvaluator", " Names"))
        self.text_names.setStatusTip(_translate("NameEvaluator", "Enter all names to be checked against here"))
        self.btn_check_names.setStatusTip(_translate("NameEvaluator", "Commit and run names against all selected avoids"))
        self.btn_check_names.setText(_translate("NameEvaluator", "Check Names"))
        self.btn_upper_case.setStatusTip(_translate("NameEvaluator", "Set all names to uppercase"))
        self.btn_upper_case.setText(_translate("NameEvaluator", "ABC"))
        self.btn_title_case.setStatusTip(_translate("NameEvaluator", "Set all names to title case"))
        self.btn_title_case.setText(_translate("NameEvaluator", "Abc"))
        self.btn_lower_case.setStatusTip(_translate("NameEvaluator", "Set all names to lowercase"))
        self.btn_lower_case.setText(_translate("NameEvaluator", "abc"))
        self.name_conflict_label.setText(_translate("NameEvaluator", "Conflicts"))
        self.qtable_results.setStatusTip(_translate("NameEvaluator", "Results of avoid checks here"))
        self.lineedit_ignore.setStatusTip(_translate("NameEvaluator", "Enter a INN stems to be ignored (e.g vir, axo, imex)"))
        self.lineedit_ignore.setPlaceholderText(_translate("NameEvaluator", "Enter INN stems to ignore here... (e.g. vir, axo, imex)"))
        self.btn_exit.setStatusTip(_translate("NameEvaluator", "Exit Name Checker"))
        self.btn_exit.setText(_translate("NameEvaluator", "      Exit      "))
        self.MainTab.setTabText(self.MainTab.indexOf(self.main_tab), _translate("NameEvaluator", "Main"))
        self.btn_reload_avoids.setText(_translate("NameEvaluator", "Reload Avoids"))
        self.btn_filter_avoids.setText(_translate("NameEvaluator", "Search"))
        self.lineedit_filter_avoids.setPlaceholderText(_translate("NameEvaluator", "Filter avoids"))
        self.btn_clear_avoid_filter.setText(_translate("NameEvaluator", "Clear Filter"))
        self.label_all_avoids.setText(_translate("NameEvaluator", "All Avoids"))
        self.label_project_avoids.setText(_translate("NameEvaluator", "Project Avoids to Add"))
        self.label_competitor.setText(_translate("NameEvaluator", "Competitor to Add"))
        self.btn_save_avoids.setText(_translate("NameEvaluator", "Save Avoids"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.avoids_tab), _translate("NameEvaluator", "View/Add Avoids"))
        self.actionExit.setText(_translate("NameEvaluator", "Leave"))
        self.actionView_pharma_avoids.setText(_translate("NameEvaluator", "View Pharma Avoids"))
        self.actionView_pharma_avoids.setStatusTip(_translate("NameEvaluator", "View Pharma Avoids"))
        self.actionView_inn_avoids.setText(_translate("NameEvaluator", "View INN Avoids"))
        self.actionProject_avoids.setText(_translate("NameEvaluator", "Project Avoids"))
        self.actionInternal_names.setText(_translate("NameEvaluator", "Internal Names"))
        self.actionPresented_names.setText(_translate("NameEvaluator", "Presented Names"))
        self.actionCompetitor_names.setText(_translate("NameEvaluator", "Competitor Names"))
        self.actionOptions.setText(_translate("NameEvaluator", "Options"))
        self.actionOptions.setStatusTip(_translate("NameEvaluator", "View Options"))
        self.actionTool_1.setText(_translate("NameEvaluator", "Tool 1"))
        self.actionTool_style.setText(_translate("NameEvaluator", "Tool 2"))
        self.actionTool_3.setText(_translate("NameEvaluator", "Tool 3"))
        self.actionTool_4.setText(_translate("NameEvaluator", "Tool 4"))
        self.actionTool_5.setText(_translate("NameEvaluator", "Tool 5"))
        self.actionSave_names.setText(_translate("NameEvaluator", "Commit Names"))
        self.actionSort_names.setText(_translate("NameEvaluator", "Sort Names (A-Z)"))
        self.actionFind_conflicts.setText(_translate("NameEvaluator", "Find Conflicts"))
        self.actionClear_avoids.setText(_translate("NameEvaluator", "Clear All Avoids"))
        self.actionView_stripped_names.setText(_translate("NameEvaluator", "View names without rationale"))
        self.actionINN_avoids_password_required.setText(_translate("NameEvaluator", "INN avoids (password req.)"))
        self.actionPharma_Avoids_password_req.setText(_translate("NameEvaluator", "Pharma Avoids (password req.)"))
        self.actionINN_avoids.setText(_translate("NameEvaluator", "INN Avoids"))
        self.actionPharma_avoids.setText(_translate("NameEvaluator", "Pharma Avoids"))
        self.actionAdd_avoids.setText(_translate("NameEvaluator", "Add Avoids"))
import src.UI.resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NameEvaluator = QtWidgets.QMainWindow()
    ui = Ui_NameEvaluator()
    ui.setupUi(NameEvaluator)
    NameEvaluator.show()
    sys.exit(app.exec_())
